apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: Dev environment project
  sourceRepos:
    - '*'
  destinations:
    # microk8s1 cluster (Dev)
    - namespace: '*'
      server: https://192.168.4.95:16443

    # Management cluster (for root-level apps)
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
