apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test
  namespace: argocd
spec:
  description: Test environment project
  sourceRepos:
    - '*'
  destinations:
    # Allow apps to deploy to the microk8s2 cluster
    - namespace: '*'
      server: https://192.168.4.96:16443
    # Allow root-level apps to deploy to the ArgoCD management cluster
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
